### ISSUE TITLE
Headers already sent

### ISSUE THREAD

**Issue by sempasha** [asasmoyo/yii2-saml#6]
I got an Error while running metadata action:
```
[[A2018-01-12 16:09:57 [172.16.158.207][-][-][error][yii\web\HeadersAlreadySentException] exception 'yii\web\HeadersAlreadySentException' with message 'Headers already sent.' in /var/www/html/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/html/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Response->send()
#2 /var/www/html/web/index.php(12): yii\base\Application->run()
#3 {main}
```
It caused by printing metadata XML before Yii response sending. Instead of raw XML printing it should be assigned to response content.
https://github.com/asasmoyo/yii2-saml/blob/b45221ab6c51fdd8cd380fd4c459e14d94bb9806/src/actions/MetadataAction.php#L21
Should be
```php
\Yii::$app->response->content = $this->samlInstance->getMetadata();
```

**Comment by asasmoyo** [comment]
Thanks for the report!
Could you verify if it is working?

**Comment by juliardi** [comment]
Updating the MetadataAction in #7

**Comment by asasmoyo** [comment]
Thanks @juliardi!
